version: '3'
services:
  dependencymanager:
    build: services/dependencymanager
  dashboard:
    build: apps/dashboard
    ports:
     - 5002:80
  messageboard:
    build: apps/messageboard
    links:
     - dashboard
    ports:
     - 5001:80
    command: --self-public-url http://127.0.0.1:5001/
